version = 1
SPDX-PackageName = "OCM Delivery DB"
SPDX-PackageSupplier = "Jonas Brand <j.brand@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/open-component-model/delivery-db"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2024 SAP SE or an SAP affiliate company and Open Component Model contributors \\", "<j.brand@sap.com>"]
SPDX-License-Identifier = "Apache-2.0"
